name: Rent Data Scraper

on:
  schedule:
    - cron: '0 19 * * *' # 毎日19:00(UTC) = 日本時間 午前4時に実行
  workflow_dispatch: # 手動実行も可能にする

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client requests beautifulsoup4 pandas pytz

    - name: Create Google Credentials
      run: echo "${{ secrets.GCP_SA_KEY }}" > key.json

    - name: Run scraper
      run: python rent_scraper.py
